---
title: "Meta-analysis:Code_meta_data"
author: "Erika Foster"
date: "1/13/2020"
output: word_document
---

Updated: 20200930 EJF
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GOAL: 
Meta-analysis on soil organic amendment impact on soil carbon pools > 20cm in depth
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
STATS OVERVIEW:

mixed model for meta-analysis (regression?) with maximum likelihood 
       (hierarchical w study and depth as groups) 
       OR I could run different analyssis every 20cm
  -need mixed effect to account for studies with multiple amendments in 1 study (autocorrelated)
       
parameter = carbon stock 
moderators = initial soil conditions, other environmental factors, management
covariate = length of study (months)??
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WORKING ON:
1. bin by depths and run regression

2020.09.30 Meta-analysis To Do list:
1. create moderator for total N input (fert+amend N) 
      => DONE variable TN.added
2. check studies pH > 7.5 (OC reported or just TC?) / other studies can use TC/OC, but check for differences in dataset TC and OC means 
      => RESPONSE: studies w pH >7.5 that report TC also have SOC = SOC is used

3. Calculate response parameters: OC, POMC, MAOM_C, POM_N, MAOM_N, TN, yield
      =>
4. New response parameter?: Calc new response ratio Amend C/SOC (% C added) / Treatment SOC?? 
      => DONE - very high values
5. Response ratio graphs for each of these parameters (7) x 3 ( ALL (fertilized controls used if an option), zero controls, fertilized controls) 
    1. Print the response ratio on the graphs
6. Create Table 1: amendment name - C,N, application rate (min, median, mean, max) >>>> RESPONSE: box plot complete
7. Start powerpoint: put in distribution of studies: locations, histograms showing ranges of parameters => overall distribution of moderators >>> DONE! 


recheck assumptions of regression - will a meta-regression be possible with this dataset??
  
glmulti - get the df.c_ratio_all data to work -> make sure thh cf and zf dataframes are combinging correctly

   IF NOT THEN CONTINUE BELOW:
Bootstrap Qb values for different parameters - how can this incorporate ACC (strata?)? Autocorrelation w depth?
    -if depth is just another parameter, no testing of how the other parameters vary with depth...

Need to bias correct bootstrap - <50% of distribution above mean
I2 test of each moderator instead of Qb value?
Must I down weight studies with imputed error?
Can I bootstrap to check distribution of the variances?
Which moderators best explain the variance? Qw and Qb calculations (how do I get a p-value? = CIs?)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
STATS QUESTIONS:
a. Is the effect different from zero? (are there outliers of effect sizes?)
      -YES, bootrapped mean effect sizes for the global meta-analysis are diffferent from zero - both with zero control and fertlizer control (positive effect)
b. Examine degree of heterogeneity of effect sizes
        -Account for between study varition (2nd source of heterogeneity)
        -USE either Qt, or I2 is more accurate between meta-analysis comparison
c. Estimate standard deviation of studies
       (1) assume normal and S = 1 ; (2) impute from studies with data (SD/mean ratio for complete studies AND (3) regression S = alpha +beta*n)
d. Calculate weight of each study (based on sample size of control and trt) (p205)

e. Make statistical inference to derive estimates, test hypothese, make decisions based on the model
       -calculate Q for each moderator? Or calucate I2 (pg 112) 
       -bootstrappping and 95% CI on factors (p 123)
f. Meta regression (random effect = study), specifically a mixed model,  & test factor influence on the effective size (see list below of 16 factors extracted)
       -metafor mods<-cbind(a, b, c) ; mima (yi, vi, mods, method = "REML")
g. Check assumptions
       (1) fit assumptions of statisitcal models
       (2) test publicaiton bias (p219)
       (3) check stat power of tests
       (4) test sensitivity of results to inclusion/exlustion of data - does it change main conclusions
              -imputed SD, estimated 1, only complete studies
              -w and w/out the outliers
              -leave one out (studies or categories)
       (5) check manuscripts (Ch 20)
h. Discuss generaliziability and limitations
        -SE assumed rather than SD when not recorded (more conservative)
i. Gaps where more primary studies are needed?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RESEARCH QUESTIONS:
Is the overall effect of amendments positive (different from zero) on soil carbon stocks?
How does amendment stabilizaiton of SC change with depth? with time?
Do effects differ between minimum controls vs fertilzed controls?

0 *** Assess correlation of moderators*** -> find a group where moderators are not confounded and run analysis -results are different than the global effects?
Do the following moderators help predict change in soil carbon stocks:
1. Amendment type - coded to group, a couple of columns
2. Amendment rate - 
3. Amendment C:N ratio
4. C pool  
5. Time since amendment start

Environmental factors
6. MAP
7. MAT
8. MAP/MAT
9.  XXXXX place holder...
10. **Lattitude**

Initial soil proerpties
11. Texture
12. Initial SOC
13. pH

Management
14. Crop System
15. Irrigation type
16. Fertilizer input
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NOTES:
echo=false supresses code; include=false supressed output
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
COMPLETED:
        1) Make categories for each variable = cropping system (monocrop, rotation), crop type (grain, row, legume, forage), years of application, type of amendment, soil pH, SOC content intial, clay content, latitute, C rate applied, dry weight, N rate 
        2) convert SE (sm) to SD (large) (assumed it was SE (small) and convert to SD = make larger)
        3) Calculated stocks for the df.c data frame only -> no need to calculate the response ratios again, as the BD did not change and they are the same as the C concentraiton ratios **major limitation with stock calcs
        4) Imputed error in the form of SD with ratios (SD/X'mean') and regrssion SD= alpha +beta (N) ; 36% have errors reported
        5) Checked heterogeneity within meta-analysis due to different studies (section 8); calculated I2 statistic
        6) Remove correlated factors:  pH and MAT = .98 and MAT/MAP; elevation and time.n.mos (.97); elevation and MAT.MAP .76,  lat and Nfert.rate .333
                =remove elevation and MAT (keep MAT/MAP)
        7) analyze fertilized and zero controls #to combine datasets - use fertilized controls when possible= had a lower effect size (will not overestimate the effect?)


~~~~~~~~~~~~
Code that did not get rJava and glmulti to work: 
################################
#in Terminal
# sudo R CMD javareconf
# sudo R
#install.packages('rJava',,'http://www.rforge.net/') #did not work
#install.packages('rJava') ,repos = "http://cran.us.r-project.org")

# additional attempts
#a
  #dyn.load('/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/jre/lib/server/libjvm.dylib')

#b
  #packurl<-"https://cran.r-project.org/src/contrib/Archive/rJava/rJava_0.9-9.tar.gz"
  #install.packages(packurl, repos=NULL, type="source")

###########################

~~~~~~~~~~~~

################################################################################
################################################################################
################################################################################
Meta - regression old code - save

rma1 <- rma(ratio_all, vi=SD_all, 
             mods = ~ C.rate_group, 
            data=df.c, method="ML") #important to use ML (instead of REML) estimation, since log-likelihoods (& hence information criteria) are not directly comparable for models with different fixed effects
aov.rma1<-anova(rma1) #btt=1) #Wald-type test of the moderators (btt= designates which coefficient to test, or all)
res1<-residuals(rma1); plot(res1); abline(0,0)


### all studies (with fertilized and zero controls), no study weights used
#mods <- model.matrix(yi, data=data) 

all.rma.ar.nowt <- rma.mv(data=df.c, ratio_all ~ 1, random= ~depth|ACC, method="ML", V=SD_all, struct="AR") #W=w_all, 
summary(all.rma.ar.nowt) # intercept (ACC) is highly significant #AIC=23135.5065    #BIC=23148.2680
res1<-resid(all.rma.ar.nowt)
plot(res1); abline(0,0)
mean(res1, na.rm=T)
 
### NULL model, all studies, study weights used
all.rma.ar.null <- rma.mv(data=df.c, ratio_all ~ 1, random= ~depth|ACC, method="REML", V=SD_all, W= w_all, struct="AR") 
summary(all.rma.ar.null) # intercept (ACC?) is highly significant; AIC = 23136.1616 BIC=23148.9231

#check if type of control effects the model, studies weighted by n
all.rma.ar.ctrl <- rma.mv(data=df.c, ratio_all ~ control.type, random= ~depth|ACC, method="REML", V=SD_all, W= w_all, struct="AR") 
summary(all.rma.ar.ctrl) # control type not significant, only intercept

#all studies - test all categorical parameters
all.rma.ar.cat <- rma.mv(data=df.c, ratio_all ~ crop_group+irrigated+crop_system+lat_group + clay_group+ pH_group+ SOC_int_group+duration_even+C.rate_group+amend_N_kg.ha_group+amend_group, random= ~depth|ACC, method="REML", V=SD_all, W= w_all, struct="AR") #AIC 60 #BIC 82.38
summary(all.rma.ar.cat) # 
resid.all.rma.ar.cat<-resid(all.rma.ar.cat)
 plot(resid.all.rma.ar.cat)
  shapiro.test(resid.all.rma.ar.cat)

step(all.rma.ar.cat, scope=list(lower=~1,upper=formula(all.rma.ar.cat)), direction="both")

str(df.c)
#amendment group
all.rma.ar.am <- rma.mv(data=df.c, ratio_all ~ amend_group, random= ~depth|ACC, method="REML", V=SD_all, W= w_all, struct="AR") #AIC 22297.7524 BIC 22348.5888
summary(all.rma.ar.am) #  

#all studies - test all continous parameters #doesn't work
 

#INTERESTING:
### effect of furrow irrigaiton
names(df)
#categorical: amend_group, amend, crop_group, irrigation, crop_system
   #made categoricals: lat_group, clay_group, pH_group, SOC_int_group, Nfert_group, C.rate_group
#continuous: C.rate_Mg.ha, C.N_rate, N.amend_g.kg, exp_duration_mos, Nfert_rate
   #env continuous: MAT, MAP, MAP/MAT, lat.dec.degree
    #initial continuous: SOC_g.kg, pH, clay


#####################################################################
### A.  studies with fertilized control 
#####################################################################
#null model, intercept only 
cf.rma.ar0 <- rma.mv(data=mydf.cf, ratio_cf ~ 1, random= ~depth|ACC,   V=SD_cf_imp, W= w.cf, method="REML", struct="AR") ; summary(cf.rma.ar0) #AIC = 516.33 (lower AIC = better fit)
     #nested hierarchical model accounts for similarities between depths within the same ACC - only allows 2 levels

cf.rma.ar.nowt <- rma.mv(data=mydf.cf, ratio_cf ~ 1, random= ~depth|ACC,   V=SD_cf_imp,  method="REML", struct="AR") ; summary(cf.rma.ar.nowt) #AIC 515.86 ; no weights W=w.cf removed

cf.rma.ar.test <- rma.mv(data=mydf.cf, ratio_cf ~ MAP+clay+amend_group, random= ~depth|ACC,   V=SD_cf_imp, W= w.cf, method="REML", struct="AR") ; summary(cf.rma.ar.test) #AIC 160.10
str(mydf.zf)

names(df)

#categorical: amend_group, amend, crop_group, irrigation, crop_system, 
#continuous: C.rate_Mg.ha, C.N_rate, N.amend_g.kg, exp_duration_mos, Nfert_rate
   #env continuous: MAT, MAP, MAP/MAT, lat.dec.degree
    #initial continuous: SOC_g.kg, pH, clay

#####################################################################
### B. studies with zero fertilizer input controls
#####################################################################
zf.rma.ar0 <- rma.mv(data=mydf.zf, ratio_zf ~ 1, random= ~depth|ACC,   V=SD_zf_imp, W= w.zf, method="REML", struct="AR") ; summary(zf.rma.ar0) #AIC = 386.08 (lower AIC = better fit)

zf.rma.ar.nowt <- rma.mv(data=mydf.zf, ratio_zf ~ 1,  V=SD_zf_imp, method="REML", struct="AR") #level=95 

zf.rma.ar.test <- rma.mv(data=dmydf.zf, ratio_zf ~ MAP+clay+amend_group,  V=SD_cf_imp, W=w.cf, method="REML") #level=95 
zf.rma.ar.test

zf.rma1 <- rma.mv(data=mydf.zf, ratio_zf ~ weight.dry , random= ~depth|ACC,   V=SD_cf_imp, W= w.cf, method="REML", struct="AR") #level=95 

#from github Gurevitch et al https://github.com/KatharinaGerstner/LUBDES_MA :

#rma.mv(yi=Log.RR, V=M.matrix(modelDataRichness)+diag(Log.RR.Var),mods=~LUI.range.level-1, 
#                                random = list(~1|Study.Case, ~1|Study.ID),
#                             slab=paste(Study.Case, Low.LUI, High.LUI,sep="_"),
#                    method="REML", tdist=FALSE, level=95,digits=4,data=modelDataRichness)       
# Viechtbauer 2015 p 189: the random argument can also contain one (and only one!) formula of the form ~ inner | outer . 
#   Effects or outcomes with different values/levels of the outer grouping variable/factor are assumed to be 
#   independent, while effects or outcomes with the same value/level of the outer grouping variable/factor share 
#   correlated random effects corresponding to the levels of the inner grouping variable/factor


################################################################################
################################################################################
################################################################################
Code using glmulit and rma as a function:

#### Example online ##################################################################
#rma.glmulti2 <- function(formula, data, ...){
#   rma(formula, vi, data=data, method="ML", ...) #vi = variance ; weights = weight
#res <- glmulti(yi ~ length + wic + feedback + info + pers + imag + meta, data=dat,
#               level=1, fitfunction=rma.glmulti, crit="aicc", confsetsize=128) }  #With level = 1, we stick to models with main effects only 
#################################################################################### 

rma.glmulti.w <- function(formula, vi, weights, random, data){
d.w<-rma(formula, vi, weights, data, random, method="ML", struct="AR")  #important to use ML (instead of REML) estimation, since log-likelihoods (& hence information criteria) are not directly comparable for models with different fixed effects
rma.glmulti.w(df.rma$ratio_all ~ df.rma$crop_group + df.rma$irrigation + df.rma$crop_system + df.rma$lat_group +df.rma$clay_group + df.rma$pH_group + df.rma$SOC_int_group, vi=df.rma$SD_all, weights=df.rma$w_all, random=~df.rma$depth|df.rma$ACC, data=df.rma)

length(df.rma$w_all) 
length(df.rma$ratio_all)

View(df.rma)

################################

res.all <- glmulti(ratio_all ~ crop_group + irrigation + crop_system + lat_group +clay_group + pH_group + SOC_int_group + duration_even + C.rate_group + amend_N_kg.ha_group + amend_group + MAP, vi=df.c$SD_all, data=df.c,random=~depth|ACC,
               level=1, fitfunction=rma.glmulti, crit="aicc", confsetsize=4096)
#With level = 1, we stick to models with main effects only; CI = 95% default
################################################################################

res <- glmulti(data=df.c, ratio_all ~ crop_group + irrigated + crop_system + lat_group + clay_group + pH_group + SOC_int_group + duration_even + C.rate_group + amend_N_kg.ha_group + amend_group + MAP, 
               random=~depth|ACC,
               vi= df.c$w_all, V=df.c$SD_all,
               level=1, fitfunction=rma.glmulti, crit="aicc", confsetsize=4096) #confsetsize = 2^12

df.c$w_all
res <- glmulti(data=df.c, ratio_all ~ crop_group + irrigation + crop_system + lat_group + clay_group + pH_group + SOC_int_group + duration_even + C.rate_group + amend_N_kg.ha_group + amend_group + MAP, 
                vi=df.c$SD_all  , random=~depth|ACC,
               level=1, fitfunction=rma.glmulti, crit="aicc", confsetsize=2^12) 
#level =1 main effects only

res <- glmulti(yi ~ length + wic + feedback + info + pers + imag + meta, data=dat,
               level=1, fitfunction=rma.glmulti, crit="aicc", confsetsize=128)


all.rma.ar.nowt <- rma.mv(data=df.c, ratio_all ~ 1, random= ~depth|ACC, method="REML", V=SD_all, struct="AR")

################################################################################
################################################################################
################################################################################

#min, median, mean, max
my.amend<-df$amend_group
df %>% group_by(amend_group) %>% summarise(my.n = n()) -> my.n

#df %>%  group_by(amend_group) %>%  summarize(min = min(amend_N_kg.ha, na.rm=T), mean = mean(amend_N_kg.ha, na.rm=T), max = max(amend_N_kg.ha, na.rm=T) ) -> my.Nrate
#df %>%  group_by(amend_group) %>%  summarize(min = min(C.rate_Mg.ha), mean = mean(C.rate_Mg.ha), max = max(C.rate_Mg.ha) ) -> my.Crate
